name: 'aena_dwh'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  aena_dwh:
    silver: # en vez de llamarlo staying lo he llamado silver
      +schema: SILVER
      +materialized: incremental
    gold: # en vez de llamarlo marts lo he llamado gold
      +schema: GOLD
      dims:
        +materialized: table
      facts:
        +materialized: incremental